### ISSUE TITLE
파이썬 3.7 지원은 아직 안되나요?ㅠ 

### ISSUE THREAD

**Issue by iuwios** [devkingsejong/python-PowerNad#11]
임포트가 안되네요  혹시 파이썬 3.7 버전이라서 그런가요?ㅠ 

>>> from powernad.API import RelKwdStat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powernad/API/RelKwdStat.py", line 1, in <module>
    from powernad.Connector.restapi import RestApi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/powernad/Connector/restapi.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by devkingsejong** [comment]
pip install requests 부탁드립니다 :)
혹시 직접 다운로드 받으신가요 아니면 pip로 받으시건가요?
